//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITG.Brix.EccSetup.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustomFailures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomFailures() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITG.Brix.EccSetup.Application.Resources.CustomFailures", typeof(CustomFailures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusinessUnit not found.
        /// </summary>
        public static string BusinessUnitNotFound {
            get {
                return ResourceManager.GetString("BusinessUnitNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklist not found.
        /// </summary>
        public static string ChecklistNotFound {
            get {
                return ResourceManager.GetString("ChecklistNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusinessUnit was not created.
        /// </summary>
        public static string CreateBusinessUnitFailure {
            get {
                return ResourceManager.GetString("CreateBusinessUnitFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklist was not created.
        /// </summary>
        public static string CreateChecklistFailure {
            get {
                return ResourceManager.GetString("CreateChecklistFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer was not created.
        /// </summary>
        public static string CreateCustomerFailure {
            get {
                return ResourceManager.GetString("CreateCustomerFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Code was not created.
        /// </summary>
        public static string CreateDamageCodeFailure {
            get {
                return ResourceManager.GetString("CreateDamageCodeFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow was not created.
        /// </summary>
        public static string CreateFlowFailure {
            get {
                return ResourceManager.GetString("CreateFlowFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon was not created.
        /// </summary>
        public static string CreateIconFailure {
            get {
                return ResourceManager.GetString("CreateIconFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information was not created.
        /// </summary>
        public static string CreateInformationFailure {
            get {
                return ResourceManager.GetString("CreateInformationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input was not created.
        /// </summary>
        public static string CreateInputFailure {
            get {
                return ResourceManager.GetString("CreateInputFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction was not created.
        /// </summary>
        public static string CreateInstructionFailure {
            get {
                return ResourceManager.GetString("CreateInstructionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout was not created.
        /// </summary>
        public static string CreateLayoutFailure {
            get {
                return ResourceManager.GetString("CreateLayoutFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location was not created.
        /// </summary>
        public static string CreateLocationFailure {
            get {
                return ResourceManager.GetString("CreateLocationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operational Department was not created.
        /// </summary>
        public static string CreateOperationalDepartmentFailure {
            get {
                return ResourceManager.GetString("CreateOperationalDepartmentFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation was not created.
        /// </summary>
        public static string CreateOperationFailure {
            get {
                return ResourceManager.GetString("CreateOperationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator activity was not created.
        /// </summary>
        public static string CreateOperatorActivityFailure {
            get {
                return ResourceManager.GetString("CreateOperatorActivityFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductSite was not created.
        /// </summary>
        public static string CreateProductionSiteFailure {
            get {
                return ResourceManager.GetString("CreateProductionSiteFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark was not created.
        /// </summary>
        public static string CreateRemarkFailure {
            get {
                return ResourceManager.GetString("CreateRemarkFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site was not created.
        /// </summary>
        public static string CreateSiteFailure {
            get {
                return ResourceManager.GetString("CreateSiteFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source was not created.
        /// </summary>
        public static string CreateSourceFailure {
            get {
                return ResourceManager.GetString("CreateSourceFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StorageStatus was not created.
        /// </summary>
        public static string CreateStorageStatusFailure {
            get {
                return ResourceManager.GetString("CreateStorageStatusFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransportType was not created.
        /// </summary>
        public static string CreateTransportTypeFailure {
            get {
                return ResourceManager.GetString("CreateTransportTypeFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypePlanning was not created.
        /// </summary>
        public static string CreateTypePlanningFailure {
            get {
                return ResourceManager.GetString("CreateTypePlanningFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation was not created.
        /// </summary>
        public static string CreateValidationFailure {
            get {
                return ResourceManager.GetString("CreateValidationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusinessUnit was not deleted.
        /// </summary>
        public static string DeleteBusinessUnitFailure {
            get {
                return ResourceManager.GetString("DeleteBusinessUnitFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklist was not deleted.
        /// </summary>
        public static string DeleteChecklistFailure {
            get {
                return ResourceManager.GetString("DeleteChecklistFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow was not deleted.
        /// </summary>
        public static string DeleteFlowFailure {
            get {
                return ResourceManager.GetString("DeleteFlowFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon was not deleted.
        /// </summary>
        public static string DeleteIconFailure {
            get {
                return ResourceManager.GetString("DeleteIconFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information was not deleted.
        /// </summary>
        public static string DeleteInformationFailure {
            get {
                return ResourceManager.GetString("DeleteInformationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input was not deleted.
        /// </summary>
        public static string DeleteInputFailure {
            get {
                return ResourceManager.GetString("DeleteInputFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction was not deleted.
        /// </summary>
        public static string DeleteInstructionFailure {
            get {
                return ResourceManager.GetString("DeleteInstructionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout was not deleted.
        /// </summary>
        public static string DeleteLayoutFailure {
            get {
                return ResourceManager.GetString("DeleteLayoutFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation was not deleted.
        /// </summary>
        public static string DeleteOperationFailure {
            get {
                return ResourceManager.GetString("DeleteOperationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark was not deleted.
        /// </summary>
        public static string DeleteRemarkFailure {
            get {
                return ResourceManager.GetString("DeleteRemarkFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source was not deleted.
        /// </summary>
        public static string DeleteSourceFailure {
            get {
                return ResourceManager.GetString("DeleteSourceFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation was not deleted.
        /// </summary>
        public static string DeleteValidationFailure {
            get {
                return ResourceManager.GetString("DeleteValidationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File cannot be downloaded.
        /// </summary>
        public static string DownloadFileFailure {
            get {
                return ResourceManager.GetString("DownloadFileFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow not found.
        /// </summary>
        public static string FlowNotFound {
            get {
                return ResourceManager.GetString("FlowNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusinessUnit cannot be read.
        /// </summary>
        public static string GetBusinessUnitFailure {
            get {
                return ResourceManager.GetString("GetBusinessUnitFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklist cannot be read.
        /// </summary>
        public static string GetChecklistFailure {
            get {
                return ResourceManager.GetString("GetChecklistFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow cannot be read.
        /// </summary>
        public static string GetFlowFailure {
            get {
                return ResourceManager.GetString("GetFlowFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon cannot be read.
        /// </summary>
        public static string GetIconFailure {
            get {
                return ResourceManager.GetString("GetIconFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information cannot be read.
        /// </summary>
        public static string GetInformationFailure {
            get {
                return ResourceManager.GetString("GetInformationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input cannot be read.
        /// </summary>
        public static string GetInputFailure {
            get {
                return ResourceManager.GetString("GetInputFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction cannot be read.
        /// </summary>
        public static string GetInstructionFailure {
            get {
                return ResourceManager.GetString("GetInstructionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout cannot be read.
        /// </summary>
        public static string GetLayoutFailure {
            get {
                return ResourceManager.GetString("GetLayoutFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cannot be read.
        /// </summary>
        public static string GetOperationFailure {
            get {
                return ResourceManager.GetString("GetOperationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark cannot be read.
        /// </summary>
        public static string GetRemarkFailure {
            get {
                return ResourceManager.GetString("GetRemarkFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source cannot be read.
        /// </summary>
        public static string GetSourceFailure {
            get {
                return ResourceManager.GetString("GetSourceFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation cannot be read.
        /// </summary>
        public static string GetValidationFailure {
            get {
                return ResourceManager.GetString("GetValidationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon not found.
        /// </summary>
        public static string IconNotFound {
            get {
                return ResourceManager.GetString("IconNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information not found.
        /// </summary>
        public static string InformationNotFound {
            get {
                return ResourceManager.GetString("InformationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input not found.
        /// </summary>
        public static string InputNotFound {
            get {
                return ResourceManager.GetString("InputNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction not found.
        /// </summary>
        public static string InstructionNotFound {
            get {
                return ResourceManager.GetString("InstructionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout not found.
        /// </summary>
        public static string LayoutNotFound {
            get {
                return ResourceManager.GetString("LayoutNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusinessUnits cannot be read.
        /// </summary>
        public static string ListBusinessUnitFailure {
            get {
                return ResourceManager.GetString("ListBusinessUnitFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklists cannot be read.
        /// </summary>
        public static string ListChecklistFailure {
            get {
                return ResourceManager.GetString("ListChecklistFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers cannot be read.
        /// </summary>
        public static string ListCustomerFailure {
            get {
                return ResourceManager.GetString("ListCustomerFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Codes cannot be read.
        /// </summary>
        public static string ListDamageCodeFailure {
            get {
                return ResourceManager.GetString("ListDamageCodeFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flows cannot be read.
        /// </summary>
        public static string ListFlowFailure {
            get {
                return ResourceManager.GetString("ListFlowFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons cannot be read.
        /// </summary>
        public static string ListIconFailure {
            get {
                return ResourceManager.GetString("ListIconFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations cannot be read.
        /// </summary>
        public static string ListInformationFailure {
            get {
                return ResourceManager.GetString("ListInformationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputs cannot be read.
        /// </summary>
        public static string ListInputFailure {
            get {
                return ResourceManager.GetString("ListInputFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions cannot be read.
        /// </summary>
        public static string ListInstructionFailure {
            get {
                return ResourceManager.GetString("ListInstructionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layouts cannot be read.
        /// </summary>
        public static string ListLayoutFailure {
            get {
                return ResourceManager.GetString("ListLayoutFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations cannot be read.
        /// </summary>
        public static string ListLocationFailure {
            get {
                return ResourceManager.GetString("ListLocationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operational Departments cannot be read.
        /// </summary>
        public static string ListOperationalDepartmentFailure {
            get {
                return ResourceManager.GetString("ListOperationalDepartmentFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations cannot be read.
        /// </summary>
        public static string ListOperationFailure {
            get {
                return ResourceManager.GetString("ListOperationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator activities cannot be read.
        /// </summary>
        public static string ListOperatorActivitiesFailure {
            get {
                return ResourceManager.GetString("ListOperatorActivitiesFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductionSite cannot be read.
        /// </summary>
        public static string ListProductionSiteFailure {
            get {
                return ResourceManager.GetString("ListProductionSiteFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks cannot be read.
        /// </summary>
        public static string ListRemarkFailure {
            get {
                return ResourceManager.GetString("ListRemarkFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sites cannot be read.
        /// </summary>
        public static string ListSiteFailure {
            get {
                return ResourceManager.GetString("ListSiteFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources cannot be read.
        /// </summary>
        public static string ListSourceFailure {
            get {
                return ResourceManager.GetString("ListSourceFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage status cannot be read.
        /// </summary>
        public static string ListStorageStatusFailure {
            get {
                return ResourceManager.GetString("ListStorageStatusFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransportType cannot be read.
        /// </summary>
        public static string ListTransportTypeFailure {
            get {
                return ResourceManager.GetString("ListTransportTypeFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypePlanning cannot be read.
        /// </summary>
        public static string ListTypePlanningFailure {
            get {
                return ResourceManager.GetString("ListTypePlanningFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validations cannot be read.
        /// </summary>
        public static string ListValidationFailure {
            get {
                return ResourceManager.GetString("ListValidationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation not found.
        /// </summary>
        public static string OperationNotFound {
            get {
                return ResourceManager.GetString("OperationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark not found.
        /// </summary>
        public static string RemarkNotFound {
            get {
                return ResourceManager.GetString("RemarkNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query parameter $skip must be a sequence of digits..
        /// </summary>
        public static string SkipInvalid {
            get {
                return ResourceManager.GetString("SkipInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query parameter $skip must be greater or equal to 0 and less than {0}..
        /// </summary>
        public static string SkipRange {
            get {
                return ResourceManager.GetString("SkipRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source not found.
        /// </summary>
        public static string SourceNotFound {
            get {
                return ResourceManager.GetString("SourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query parameter $top must be a sequence of digits..
        /// </summary>
        public static string TopInvalid {
            get {
                return ResourceManager.GetString("TopInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query parameter $top must be greater than 0 and less than {0}..
        /// </summary>
        public static string TopRange {
            get {
                return ResourceManager.GetString("TopRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusinessUnit was not updated.
        /// </summary>
        public static string UpdateBusinessUnitFailure {
            get {
                return ResourceManager.GetString("UpdateBusinessUnitFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklist was not updated.
        /// </summary>
        public static string UpdateChecklistFailure {
            get {
                return ResourceManager.GetString("UpdateChecklistFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow was not updated.
        /// </summary>
        public static string UpdateFlowFailure {
            get {
                return ResourceManager.GetString("UpdateFlowFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon was not updated.
        /// </summary>
        public static string UpdateIconFailure {
            get {
                return ResourceManager.GetString("UpdateIconFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information was not updated.
        /// </summary>
        public static string UpdateInformationFailure {
            get {
                return ResourceManager.GetString("UpdateInformationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input was not updated.
        /// </summary>
        public static string UpdateInputFailure {
            get {
                return ResourceManager.GetString("UpdateInputFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction was not updated.
        /// </summary>
        public static string UpdateInstructionFailure {
            get {
                return ResourceManager.GetString("UpdateInstructionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout was not updated.
        /// </summary>
        public static string UpdateLayoutFailure {
            get {
                return ResourceManager.GetString("UpdateLayoutFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation was not updated.
        /// </summary>
        public static string UpdateOperationFailure {
            get {
                return ResourceManager.GetString("UpdateOperationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark was not updated.
        /// </summary>
        public static string UpdateRemarkFailure {
            get {
                return ResourceManager.GetString("UpdateRemarkFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source was not updated.
        /// </summary>
        public static string UpdateSourceFailure {
            get {
                return ResourceManager.GetString("UpdateSourceFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation was not updated.
        /// </summary>
        public static string UpdateValidationFailure {
            get {
                return ResourceManager.GetString("UpdateValidationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was not uploaded.
        /// </summary>
        public static string UploadFileFailure {
            get {
                return ResourceManager.GetString("UploadFileFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation not found.
        /// </summary>
        public static string ValidationNotFound {
            get {
                return ResourceManager.GetString("ValidationNotFound", resourceCulture);
            }
        }
    }
}
