//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITG.Brix.EccSetup.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationFailures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationFailures() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITG.Brix.EccSetup.Application.Resources.ValidationFailures", typeof(ValidationFailures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business unit name cannot be null or empty.
        /// </summary>
        public static string BusinessUnitNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("BusinessUnitNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business unit name cannot begin or end with white space.
        /// </summary>
        public static string BusinessUnitNameCannotStartOrEndWithWhiteSpace {
            get {
                return ResourceManager.GetString("BusinessUnitNameCannotStartOrEndWithWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business unit name mandatory.
        /// </summary>
        public static string BusinessUnitNameMandatory {
            get {
                return ResourceManager.GetString("BusinessUnitNameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer code mandatory.
        /// </summary>
        public static string CustomerCodeMandatory {
            get {
                return ResourceManager.GetString("CustomerCodeMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cstomer name mandatory.
        /// </summary>
        public static string CustomerNameMandatory {
            get {
                return ResourceManager.GetString("CustomerNameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer source mandatory.
        /// </summary>
        public static string CustomerSourceMandatory {
            get {
                return ResourceManager.GetString("CustomerSourceMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DamageCode Code mandatory.
        /// </summary>
        public static string DamageCodeCodeMandatory {
            get {
                return ResourceManager.GetString("DamageCodeCodeMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DamageCode DamagedQuantityRequired mandatory.
        /// </summary>
        public static string DamageCodeDamagedQuantityRequiredMandatory {
            get {
                return ResourceManager.GetString("DamageCodeDamagedQuantityRequiredMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DamageCode is not boolean.
        /// </summary>
        public static string DamageCodeIsNotBoolean {
            get {
                return ResourceManager.GetString("DamageCodeIsNotBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DamageCode Name mandatory.
        /// </summary>
        public static string DamageCodeNameMandatory {
            get {
                return ResourceManager.GetString("DamageCodeNameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DamageCode source mandatory.
        /// </summary>
        public static string DamageCodeSourceMandatory {
            get {
                return ResourceManager.GetString("DamageCodeSourceMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow name cannot be null or empty.
        /// </summary>
        public static string FlowNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("FlowNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow name cannot begin or end with white space.
        /// </summary>
        public static string FlowNameCannotStartOrEndWithWhiteSpace {
            get {
                return ResourceManager.GetString("FlowNameCannotStartOrEndWithWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow name mandatory.
        /// </summary>
        public static string FlowNameMandatory {
            get {
                return ResourceManager.GetString("FlowNameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon data path cannot be null or empty.
        /// </summary>
        public static string IconDataPathCannotBeEmpty {
            get {
                return ResourceManager.GetString("IconDataPathCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon data path mandatory.
        /// </summary>
        public static string IconDataPathMandatory {
            get {
                return ResourceManager.GetString("IconDataPathMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon name cannot be null or empty.
        /// </summary>
        public static string IconNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("IconNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon name cannot begin or end with white space.
        /// </summary>
        public static string IconNameCannotStartOrEndWithWhiteSpace {
            get {
                return ResourceManager.GetString("IconNameCannotStartOrEndWithWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon name mandatory.
        /// </summary>
        public static string IconNameMandatory {
            get {
                return ResourceManager.GetString("IconNameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information name cannot begin or end with white space.
        /// </summary>
        public static string InformationNameCannotStartOrEndWithWhiteSpace {
            get {
                return ResourceManager.GetString("InformationNameCannotStartOrEndWithWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information name mandatory.
        /// </summary>
        public static string InformationNameMandatory {
            get {
                return ResourceManager.GetString("InformationNameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information tag mandatory.
        /// </summary>
        public static string InformationTagMandatory {
            get {
                return ResourceManager.GetString("InformationTagMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input name cannot begin or end with white space.
        /// </summary>
        public static string InputNameCannotStartOrEndWithWhiteSpace {
            get {
                return ResourceManager.GetString("InputNameCannotStartOrEndWithWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input name mandatory.
        /// </summary>
        public static string InputNameMandatory {
            get {
                return ResourceManager.GetString("InputNameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input tag mandatory.
        /// </summary>
        public static string InputTagMandatory {
            get {
                return ResourceManager.GetString("InputTagMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction content mandatory.
        /// </summary>
        public static string InstructionContentMandatory {
            get {
                return ResourceManager.GetString("InstructionContentMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction name cannot begin or end with white space.
        /// </summary>
        public static string InstructionNameCannotStartOrEndWithWhiteSpace {
            get {
                return ResourceManager.GetString("InstructionNameCannotStartOrEndWithWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction name mandatory.
        /// </summary>
        public static string InstructionNameManadatory {
            get {
                return ResourceManager.GetString("InstructionNameManadatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction name mandatory.
        /// </summary>
        public static string InstructionNameMandatory {
            get {
                return ResourceManager.GetString("InstructionNameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction tag mandatory.
        /// </summary>
        public static string InstructionTagMandatory {
            get {
                return ResourceManager.GetString("InstructionTagMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout name cannot be null or empty.
        /// </summary>
        public static string LayoutNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("LayoutNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout name cannot begin or end with white space.
        /// </summary>
        public static string LayoutNameCannotStartOrEndWithWhiteSpace {
            get {
                return ResourceManager.GetString("LayoutNameCannotStartOrEndWithWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout name mandatory.
        /// </summary>
        public static string LayoutNameMandatory {
            get {
                return ResourceManager.GetString("LayoutNameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Gate mandatory.
        /// </summary>
        public static string LocationGateMandatory {
            get {
                return ResourceManager.GetString("LocationGateMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location IsRack mandatory.
        /// </summary>
        public static string LocationIsRackMandatory {
            get {
                return ResourceManager.GetString("LocationIsRackMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsRack  field not boolean.
        /// </summary>
        public static string LocationIsRackNotBoolean {
            get {
                return ResourceManager.GetString("LocationIsRackNotBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Position mandatory.
        /// </summary>
        public static string LocationPositionMandatory {
            get {
                return ResourceManager.GetString("LocationPositionMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Row mandatory.
        /// </summary>
        public static string LocationRowMandatory {
            get {
                return ResourceManager.GetString("LocationRowMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Site mandatory.
        /// </summary>
        public static string LocationSiteMandatory {
            get {
                return ResourceManager.GetString("LocationSiteMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location  Source mandatory.
        /// </summary>
        public static string LocationSourceMandatory {
            get {
                return ResourceManager.GetString("LocationSourceMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Type mandatory.
        /// </summary>
        public static string LocationTypeMandatory {
            get {
                return ResourceManager.GetString("LocationTypeMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Warehouse mandatory.
        /// </summary>
        public static string LocationWarehouseMandatory {
            get {
                return ResourceManager.GetString("LocationWarehouseMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name manadatory.
        /// </summary>
        public static string NameMandatory {
            get {
                return ResourceManager.GetString("NameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operational Department code mandatory..
        /// </summary>
        public static string OperationalDepartmentCodeMandatory {
            get {
                return ResourceManager.GetString("OperationalDepartmentCodeMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operational Department site mandatory..
        /// </summary>
        public static string OperationalDepartmentSiteMandatory {
            get {
                return ResourceManager.GetString("OperationalDepartmentSiteMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operational Department source mandatory..
        /// </summary>
        public static string OperationalDepartmentSourceMandatory {
            get {
                return ResourceManager.GetString("OperationalDepartmentSourceMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation description cannot be null or empty.
        /// </summary>
        public static string OperationDescriptionCannotBeEmpty {
            get {
                return ResourceManager.GetString("OperationDescriptionCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation name cannot be null or empty.
        /// </summary>
        public static string OperationNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("OperationNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation name cannot begin or end with white space.
        /// </summary>
        public static string OperationNameCannotStartOrEndWithWhiteSpace {
            get {
                return ResourceManager.GetString("OperationNameCannotStartOrEndWithWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation name mandatory.
        /// </summary>
        public static string OperationNameMandatory {
            get {
                return ResourceManager.GetString("OperationNameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductionSite code mandatory.
        /// </summary>
        public static string ProductionSiteCodeMandatory {
            get {
                return ResourceManager.GetString("ProductionSiteCodeMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductionSIte name mandatory.
        /// </summary>
        public static string ProductionSiteNameMandatory {
            get {
                return ResourceManager.GetString("ProductionSiteNameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductionSite source mandatory.
        /// </summary>
        public static string ProductionSiteSourceMandatory {
            get {
                return ResourceManager.GetString("ProductionSiteSourceMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark name cannot begin or end with white space.
        /// </summary>
        public static string RemarkNameCannotStartOrEndWithWhiteSpace {
            get {
                return ResourceManager.GetString("RemarkNameCannotStartOrEndWithWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark name manadatory.
        /// </summary>
        public static string RemarkNameMandatory {
            get {
                return ResourceManager.GetString("RemarkNameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Code mandatory.
        /// </summary>
        public static string SiteCodeMandatory {
            get {
                return ResourceManager.GetString("SiteCodeMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Source mandatory.
        /// </summary>
        public static string SiteSourceMandatory {
            get {
                return ResourceManager.GetString("SiteSourceMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source business unit mandatory.
        /// </summary>
        public static string SourceBusinessUnitMandatory {
            get {
                return ResourceManager.GetString("SourceBusinessUnitMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source description cannot be null or empty.
        /// </summary>
        public static string SourceDescriptionCannotBeEmpty {
            get {
                return ResourceManager.GetString("SourceDescriptionCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source description mandatory.
        /// </summary>
        public static string SourceDescriptionMandatory {
            get {
                return ResourceManager.GetString("SourceDescriptionMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source name cannot be null or empty.
        /// </summary>
        public static string SourceNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("SourceNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source name cannot begin or end with white space.
        /// </summary>
        public static string SourceNameCannotStartOrEndWithWhiteSpace {
            get {
                return ResourceManager.GetString("SourceNameCannotStartOrEndWithWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source name mandatory.
        /// </summary>
        public static string SourceNameMandatory {
            get {
                return ResourceManager.GetString("SourceNameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StorageStatus code mandatory.
        /// </summary>
        public static string StorageStatusCodeMandatory {
            get {
                return ResourceManager.GetString("StorageStatusCodeMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StorageStatus default mandatory.
        /// </summary>
        public static string StorageStatusDefaultMandatory {
            get {
                return ResourceManager.GetString("StorageStatusDefaultMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StorageStatus default not boolean.
        /// </summary>
        public static string StorageStatusDefaultNotBoolean {
            get {
                return ResourceManager.GetString("StorageStatusDefaultNotBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StorageStatus name mandatory.
        /// </summary>
        public static string StorageStatusNameMandatory {
            get {
                return ResourceManager.GetString("StorageStatusNameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StorageStatus source mandatory.
        /// </summary>
        public static string StorageStatusSourceMandatory {
            get {
                return ResourceManager.GetString("StorageStatusSourceMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport Type code mandatory.
        /// </summary>
        public static string TransportTypeCodeMandatory {
            get {
                return ResourceManager.GetString("TransportTypeCodeMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport Type name mandatory.
        /// </summary>
        public static string TransportTypeNameMandatory {
            get {
                return ResourceManager.GetString("TransportTypeNameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport Tyape source mandatory .
        /// </summary>
        public static string TransportTypeSourceMandatory {
            get {
                return ResourceManager.GetString("TransportTypeSourceMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypePlanning code mandatory.
        /// </summary>
        public static string TypePlanningCodeMandatory {
            get {
                return ResourceManager.GetString("TypePlanningCodeMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypePlanning name mandatory.
        /// </summary>
        public static string TypePlanningNameMandatory {
            get {
                return ResourceManager.GetString("TypePlanningNameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypePlanning source mandatory.
        /// </summary>
        public static string TypePlanningSourceMandatory {
            get {
                return ResourceManager.GetString("TypePlanningSourceMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation name mandatory.
        /// </summary>
        public static string ValidationNameMandatory {
            get {
                return ResourceManager.GetString("ValidationNameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation tag mandatory.
        /// </summary>
        public static string ValidationTagMandatory {
            get {
                return ResourceManager.GetString("ValidationTagMandatory", resourceCulture);
            }
        }
    }
}
